### ISSUE TITLE
Output script descriptors

### ISSUE THREAD

**Issue by shesek** [shesek/bwt#1]

**Comment by justinmoon** [comment]
bwt seems to use xpubs to represent a range of outputs (conceptually the same thing as a a ranged descriptor), and HD origin fingerprints as public identifiers for these output ranges. Descriptor-wise, the problem is that HD fingerprints only map to a subset of descriptor wallets. Perhaps [descriptor checksums](https://github.com/bitcoin/bitcoin/blob/master/doc/descriptors.md#checksums) could serve this same purpose for wallets anchored to a ranged descriptor instead of an xpub?

You are currently marking every exported address with a `{origin}/{index}` label. You could switch this to `{ranged_descriptor_checksum}/{ranged_descriptor_index}`.

You could call `importmulti` with a (non-ranged) descriptor argument instead of the current `address` argument. Just replace every `*` in ranged descriptor with an index. Using a non-ranged descriptor allows you to bypass [this issue](https://github.com/shesek/bwt/blob/master/src/hd.rs#L346). In light of #2, it's a potentially superior address import method because origin information contained inside the descriptor can be included in PSBTs generated with `walletcreatefundedpsbt` (just set `bip32derivs` to `true` in `walletcreatefundedpsbt` call).

I've only spent a few hours looking at bwt so I could be totally wrong, but it seems like this approach would be strictly more capable than the current xpub-based approach.

Note: @afilini has published Rust implementation of [descriptor checksums](https://github.com/MagicalBitcoin/magical-bitcoin-wallet/blob/master/src/descriptor/checksum.rs) and [ranged descriptors](https://github.com/MagicalBitcoin/magical-bitcoin-wallet/blob/master/src/descriptor/extended_key.rs) which may be useful here.

**Comment by shesek** [comment]
Making the xpub/extkey a specialized case of descriptors and replacing the key fingerprint with a descriptor fingerprint is what I had in mind for supporting descriptors. The descriptors would be how things are implemented under the hood, with some conveniences for users that prefer to think in terms of xpub wallets.

(So users could specify an [xyz]pub and have it converted to a descriptor, and possibly also keep a map around for converting extkey_fingerprint -> descriptor_fingerprint to maintain compatibility with the current key-fingerprint-based endpoints, such that `/hd/:fingerprint/:index` would still work but internally delegate to the matching descriptor.)

> You could call `importmulti` with a (non-ranged) descriptor argument 

You're right that using non-ranged descriptor imports with a label would give best of both worlds - bwt will have its label for quick access, and bitcoind will have its descriptor/origin information for PSBT.

> I've only spent a few hours looking at bwt so I could be totally wrong, but it seems like this approach would be strictly more capable than the current xpub-based approach.

You're absolutely correct; I just didn't get around to that yet. :-)

> Note: @afilini has published Rust implementations of [descriptor checksums](https://github.com/MagicalBitcoin/magical-bitcoin-wallet/blob/master/src/descriptor/checksum.rs) and [ranged descriptors](https://github.com/MagicalBitcoin/magical-bitcoin-wallet/blob/master/src/descriptor/extended_key.rs) which may be useful here.

That's pretty useful, thanks for the links!

**Comment by shesek** [comment]
Descriptor-based tracking is nearly ready on the [202010-descriptor branch](https://github.com/shesek/bwt/commits/202010-descriptor).

This is how the new API looks like: https://gist.github.com/shesek/bf357a55c968635d34adfd171d0c65b1

**Comment by shesek** [comment]
Merged to master! The bulk of the changes are in https://github.com/shesek/bwt/commit/d305ec9ac4b5ecac19f0728a925b67d7dee9b3f9, with a bunch of followup enhancement commits.
