### ISSUE TITLE
Support for custom paths

### ISSUE THREAD

**Issue by junderw** [shesek/bwt#32]
Given an xpub, there should be a way to override the path. Perhaps using some keywords.

If not specified the default is `%CHANGE%/%INDEX%`

ie

`CUSTOM_PATH="123/%CHANGE%/1/8/23/%INDEX%/2/4"`

will result in the first receive address paths of:

- 123/0/1/8/23/0/2/4
- 123/0/1/8/23/1/2/4
- 123/0/1/8/23/2/2/4

and the first change address paths of:

- 123/1/1/8/23/0/2/4
- 123/1/1/8/23/1/2/4
- 123/1/1/8/23/2/2/4

Some things to consider as design choices:

1. Should it be possible to have %CHANGE% come AFTER %INDEX%
2. Should it be possible to omit %CHANGE% (if ie. an exchange would rather explicitly specify change address(es) for whatever reason)
3. Should it be further abstracted where variables like %CHANGE% and %INDEX% can be created/added and given parameters (ie. Creating a non-hardened "BIP44 Account"-like system where you only check the next number if there is tx history in any receive address of the previous number)

I would say 1=no, 2=yes, 3="someday... maybe"

**Comment by shesek** [comment]
This will be made possible with [script descriptors](https://github.com/shesek/bwt/issues/1).

In the meanwhile, bwt does support specifying a `--bare-xpub` to derive child keys directly without separate internal/external chains (just `xpub/i` instead of both `xpub/0/i` and `xpub/1/i`). But this assumes that the index is the last derivation, and so couldn't be used with some of your examples.
